### ISSUE TITLE
npm i 执行报错

### ISSUE THREAD

**Issue by rengar-top** [go-admin-team/go-admin-ui#109]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: go-admin@1.3.3
npm ERR! Found: eslint@7.6.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.13
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"^4.4.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by yaxinxiang** [comment]
npm版本过高吧,7以后的都不行
