### ISSUE TITLE
npm install  报错

### ISSUE THREAD

**Issue by kongerlengzi** [go-admin-team/go-admin-ui#110]
npm ERR! Error while executing:
npm ERR! D:\SoftWares\Git\cmd\git.EXE ls-remote -h -t https://github.com/nhn/raphael.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/nhn/raphael.git/': Failed to connect to github.com port 443: Connec
tion refused
npm ERR!
npm ERR! exited with error code: 128

**Comment by wenjianzhang** [comment]
可以使用cnpm尝试安装
