### ISSUE TITLE
修改角色权限 处于半勾选的数据没有上传到后台

### ISSUE THREAD

**Issue by lx32056127** [go-admin-team/go-admin-ui#135]
1.修改角色权限，只授予部分菜单权限时，上级节点处于半勾选状态，处于半勾选的数据没有上传到后台。

会导致授予了部分子菜单，但是顶级菜单没有。

https://github.com/go-admin-team/go-admin-ui/blob/01a21ae710b28e48945ecf90c833eb7283787576/src/views/admin/sys-role/index.vue#L379-L388

**Comment by wenjianzhang** [comment]
只需要上传选中菜单即可；
