### ISSUE TITLE
修改角色权限时，操作确定按钮之后接口一直报超时

### ISSUE THREAD

**Issue by Shi-zhenjie** [go-admin-team/go-admin-ui#138]
![image](https://user-images.githubusercontent.com/85266497/126425855-3d98444d-c54f-4e3a-b5e9-6d4681309714.png)

后台接口sys_casbin_rule接口一直请求，好像是把所有的接口都重新请求了一遍似的
![image](https://user-images.githubusercontent.com/85266497/126425613-ac3526aa-c5cd-408c-8941-13f6aaf5ef85.png)

**Comment by wenjianzhang** [comment]
这个是使用的其他开源项目，后续会做调整，可将前端的超市时间设置稍微放长
