### ISSUE TITLE
能否格式化一下下项目

### ISSUE THREAD

**Issue by freefrozenfire** [go-admin-team/go-admin-ui#143]
能否格式化一下下项目，`go fmt priject`...
好多地方编码都不符合google go code style，诸如一下不等...
1. import顺序错乱，随意；
2. 运算符前后空格；
3. 文件头尾等位置空行数量；
4. 注释双斜线空格统一；

**Comment by wenjianzhang** [comment]
伙计你是在说go-admin-ui 项目需要使用
go fmt priject ，vue里边应该没有这个cmd吧？

**Comment by misakichan** [comment]
这边是前端项目，跟go没关系的，左转去 go-admin 仓库康康
