### ISSUE TITLE
前端项目缺少行政区管理sys-china-area-data

### ISSUE THREAD

**Issue by misakichan** [go-admin-team/go-admin-ui#148]
初始化项目后 系统工具中包含行政区管理页面，组件路径为`src/views/sys-tools/sys-china-area-data/index`。实际前端项目中并没有这个.vue文件。会报错`Error: Cannot find module './views/sys-tools/sys-china-area-data/index'`

**Comment by wenjianzhang** [comment]
新版本已经移除了该功能，如果需要使用需要退回之前版本，即可；
