### ISSUE TITLE
是否可以将所有弹框改成只有点击X或者取消才能关闭

### ISSUE THREAD

**Issue by dingke198** [go-admin-team/go-admin-ui#167]
现在弹窗点击空白，或者切换输入法都会触发窗口关闭，造成一些弹窗输入信息，输入了半天，一不小心就促发关闭，又得重填，很麻烦，之前记得elment-ui里面有个弹窗属性改一下就能避免这个问题的。

**Comment by wenjianzhang** [comment]
可以根据自己的场景调整相应的配置
