### ISSUE TITLE
npm install err

### ISSUE THREAD

**Issue by 123456dawanzi** [go-admin-team/go-admin-ui#181]
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/102271362/160090965-aa4eafd6-73c8-43d9-8ef1-7ae875575e9a.png">

**Comment by wenjianzhang** [comment]
首先确认 node版本v14.16.0 和npm版本6.14.11，如果不是请调整至对应版本

**Comment by shockerli** [comment]
> 



> 首先确认 node版本v14.16.0 和npm版本6.14.11，如果不是请调整至对应版本

是否可以兼容下多版本，比如支持 npm >= 6.14.11。

**Comment by G-Akiraka** [comment]
这个自己改版本一样可以的，修改你指定版本即可
