### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by albbm** [go-admin-team/go-admin-ui#182]
npm install 报错

**Comment by nightmeng** [comment]
切换了多个版本，执行npm install报错：
![image](https://user-images.githubusercontent.com/8165086/160273083-3c51975d-7ece-4445-9420-253efb34f122.png)

版本：
{
  'go-admin': '2.0.6',
  npm: '8.5.2',
  node: '17.7.1',
  v8: '9.6.180.15-node.15',
  uv: '1.44.1',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '102',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1m',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}

**Comment by iakirago** [comment]
按照提示 npm install --legacy-peer-deps
这样安装就可以了，我也是遇到这个问题，晚上搜了一下，按照提示就可以安装成功了
