### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by chengfeiZhou** [go-admin-team/go-admin-ui#186]
```shell
npm install --registry=https://registry.npm.taobao.org
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: go-admin@2.0.6
npm ERR! Found: eslint@7.6.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.17
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"^4.4.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/chengfei/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chengfei/.npm/_logs/2022-06-08T11_22_15_068Z-debug-0.log
```
可以使用`npm i --legacy-peer-deps `的方式安装依赖;
但这是一个问题, 需要作者关注一下!!!!

**Comment by wenjianzhang** [comment]
Hello @chengfeiZhou. We totally like your proposal/feedback, welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. Please send your Pull Request to proper branch (feature branch for the new feature, master for bugfix and other changes), fill the [Pull Request Template](https://github.com/go-admin-team/go-admin/blob/master/.github/PULL_REQUEST_TEMPLATE.md) here, provide changelog/TypeScript/documentation/test cases if needed and make sure CI passed, we will review it soon. We appreciate your effort in advance and looking forward to your contribution!
你好 @chengfeiZhou，我们完全同意你的提议/反馈，欢迎直接在此仓库 [创建一个 Pull Request](https://help.github.com/en/articles/creating-a-pull-request) 来解决这个问题。请将 Pull Request 发到正确的分支（新特性发到 feature 分支，其他发到 master 分支），务必填写 Pull Request 内的[预设模板](https://github.com/go-admin-team/go-admin/blob/master/.github/PULL_REQUEST_TEMPLATE.md)，提供改动所需相应的 changelog、TypeScript 定义、测试用例、文档等，并确保 CI 通过，我们会尽快进行 Review，提前感谢和期待您的贡献。
![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif)

**Comment by GpsLypy** [comment]
![image](https://user-images.githubusercontent.com/80027734/189083334-42b32af0-8195-4f97-a8c0-8db044159452.png)
我遇到了这个问题

**Comment by linlih** [comment]
同样也遇到了这个问题。

**Comment by zouchao** [comment]
遇到相同问题

**Comment by G-Akiraka** [comment]
建议直接修改成 npm config set registry http://registry.npm.taobao.org/ 作为默认源。后续直接npm install 或者 yarn install 即可
