### ISSUE TITLE
cnpm run dev报错

### ISSUE THREAD

**Issue by yaodongzhi** [go-admin-team/go-admin-ui#189]
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                                                        3:15:14 PM

 error  in ./node_modules/_vue-particles@1.0.9@vue-particles/src/vue-particles/vue-particles.vue

Syntax Error: TypeError: Cannot read property 'styles' of undefined

 @ ./node_modules/_vue-particles@1.0.9@vue-particles/src/vue-particles/index.js 2:0-43 7:39-48
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@3.11.3@webpack-dev-server/client?http://192.168.0.102:9528&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by sqc157400661** [comment]
请问你解决了吗

**Comment by lzscxb** [comment]
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                          21:57:29

 error  in ./node_modules/_vue-particles@1.0.9@vue-particles/src/vue-particles/vue-particles.vue

Syntax Error: TypeError: Cannot read property 'styles' of undefined


 @ ./node_modules/_vue-particles@1.0.9@vue-particles/src/vue-particles/index.js 2:0-43 7:39-48
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@3.11.3@webpack-dev-server/client?http://172.20.10.6:9527&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
我也出现这个问题

**Comment by yaodongzhi** [comment]
找了我们公司的前端大佬给看了看，是版本问题，用yarn装就好了

**Comment by lzscxb** [comment]
是的，我前天使用 yarn 安装已经可以运行了，cnpm源应该是有点问题的
