### ISSUE TITLE
可以在初始化表的时候设置为utf8，适配数据库不是utf8的人

### ISSUE THREAD

**Issue by Vingurzhou** [go-admin-team/go-admin-ui#190]
err := tx.Set("gorm:table_options", "ENGINE=InnoDB DEFAULT CHARSET=utf8").Debug().Migrator().AutoMigrate(
			new(models.CasbinRule),
			new(models.SysDept),
			new(models.SysConfig),
			new(models.SysTables),
			new(models.SysColumns),
			new(models.SysMenu),
			new(models.SysLoginLog),
			new(models.SysOperaLog),
			new(models.SysRoleDept),
			new(models.SysUser),
			new(models.SysRole),
			new(models.SysPost),
			new(models.DictData),
			new(models.DictType),
			new(models.SysJob),
			new(models.SysConfig),
			new(models.SysApi),
			new(models.TbDemo),
		)

**Comment by wenjianzhang** [comment]
done
