### ISSUE TITLE
win10 npm run dev报错

### ISSUE THREAD

**Issue by spookyy** [go-admin-team/go-admin-ui#191]
Warning: 33 repetitive deprecation warnings omitted.

98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                                                                                                       10:32:42
 error  in ./node_modules/_vue-particles@1.0.9@vue-particles/src/vue-particles/vue-particles.vue

Syntax Error: TypeError: Cannot read properties of undefined (reading 'styles')

 @ ./node_modules/_vue-particles@1.0.9@vue-particles/src/vue-particles/index.js 2:0-43 7:39-48
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@3.11.3@webpack-dev-server/client?http://192.168.0.101:9527&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by 87074139** [comment]
I have the same error too

**Comment by doctorkervin** [comment]
mac has the same error ,so who can solve it

**Comment by 87074139** [comment]
node v18.2.0
npm 8.9.0
os mac
I have the same error too

**Comment by wenjianzhang** [comment]
Please try using
$ node -v
v14.16.0

$ npm -v
6.14.11

And read [doc](https://doc.go-admin.dev/guide/ksks)

**Comment by jiftle** [comment]
我也是哦。 deepin 20.7 
版本
```
cnpm@8.4.0 (/home/opt/my-apps/node/lib/node_modules/cnpm/lib/parse_argv.js)
npm@8.19.2 (/home/opt/my-apps/node/lib/node_modules/cnpm/node_modules/npm/index.js)
node@14.20.1 (/home/opt/my-apps/node/bin/node)
npminstall@6.5.2 (/home/opt/my-apps/node/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/home/opt/my-apps/node 
linux x64 5.15.45-amd64-desktop 
registry=https://registry.npmmirror.com
```

``` 
ERROR  Failed to compile with 1 error

 error  in ./node_modules/_vue-particles@1.0.9@vue-particles/src/vue-particles/vue-particles.vue

Syntax Error: TypeError: Cannot read property 'styles' of undefined


 @ ./node_modules/_vue-particles@1.0.9@vue-particles/src/vue-particles/index.js 2:0-43 7:39-48
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@3.11.3@webpack-dev-server/client?http://192.168.2.150:9527&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by weichenglan** [comment]
Iam resolve by
firstStep: 
"https://github.com/go-admin-team/go-admin-ui.git"
if you do firststep have the question
also can :
secondStep:
"https://blog.csdn.net/m0_37899432/article/details/126624076 "
just fix the package.json
"scripts": {
    "dev": "SET NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve",
    "build:prod": "SET NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service build"
  },

**Comment by weichenglan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
