### ISSUE TITLE
编译完成无法访问后端

### ISSUE THREAD

**Issue by linlih** [go-admin-team/go-admin-ui#207]
![image](https://user-images.githubusercontent.com/35171741/218317321-346178d1-1b14-4639-8b1a-57213375f49a.png)
是有什么需要修改的配置吗？

安装和执行过程也有问题：
前端npm安装时候使用这个命令，不然会报错
`npm i --legacy-peer-deps --registry=https://registry.npm.taobao.org`
安装完成后，先执行以下命令：
`export NODE_OPTIONS=--openssl-legacy-provider`
然后再执行：`npm run dev`

**Comment by G-Akiraka** [comment]
通常来说，前端配置都是127.0.0.1:8000或localhost:8000没变化情况下，后端未启动或后端端口号不对
