### ISSUE TITLE
npm run dev 如何解决elemen-ui 编译时的警告呢？

### ISSUE THREAD

**Issue by TJW8812031314** [go-admin-team/go-admin-ui#209]
Deprecation Warning: $weight: Passing a number without unit % (0) is deprecated.

To preserve current behavior: $weight * 1%

 color: mix($--tag-info-color, $--color-white, $fontColorWeight);

    node_modules\element-ui\packages\theme-chalk\src\tag.scss 24:12            genTheme()
    node_modules\element-ui\packages\theme-chalk\src\tag.scss 127:5            @content
    node_modules\element-ui\packages\theme-chalk\src\mixins\mixins.scss 112:7  m()
    node_modules\element-ui\packages\theme-chalk\src\tag.scss 126:3            @content
    node_modules\element-ui\packages\theme-chalk\src\mixins\mixins.scss 74:5   b()
    node_modules\element-ui\packages\theme-chalk\src\tag.scss 94:1             @import
    node_modules\element-ui\packages\theme-chalk\src\select.scss 6:9           @import
    node_modules\element-ui\packages\theme-chalk\src\pagination.scss 4:9       @import
    node_modules\element-ui\packages\theme-chalk\src\index.scss 2:9            @import

**Comment by wenjianzhang** [comment]
https://www.go-admin.pro/guide/faq 
<img width="924" alt="image" src="https://user-images.githubusercontent.com/3890175/229969336-d42f0399-2b5a-47cb-ba96-916d923fe676.png">
