### ISSUE TITLE
怎么把让这个项目支付node.js 20.10.0版本以上的

### ISSUE THREAD

**Issue by richardgong1987** [go-admin-team/go-admin-ui#231]
目前看来,这项目的依赖只支持nodejs: v14.16.0的版本.

怎么把让这个项目支付node.js 20.10.0版本以上的

**Comment by richardgong1987** [comment]
调查下来,发现是由于@riophae/vue-treeselect这个包造成的.而这个包在2019年就已经停止维护了... 它是基于vue2开发的.
由于这个包,造成我们用的node.js非常的老..

**Comment by thinkboy** [comment]
@richardgong1987 有动力优化下么？

**Comment by thinkboy** [comment]
相同的问题。作者似乎不怎么维护前端界面了。

**Comment by richardgong1987** [comment]
看来这项目本来想面向国际的,结果,可能大环境不好.大家忙着找工作去了.没什么人维护了..

**Comment by lwnmengjing** [comment]
> 看来这项目本来想面向国际的,结果,可能大环境不好.大家忙着找工作去了.没什么人维护了..

可以试试mss-boot-admin

**Comment by richardgong1987** [comment]
感谢. 我去看看.

**Comment by thinkboy** [comment]
> > 看来这项目本来想面向国际的,结果,可能大环境不好.大家忙着找工作去了.没什么人维护了..
> 
> 如果可以接受react，可以用go-admin的订阅版，或者可以试试mss-boot-admin

@lwnmengjing 订阅版的代码在哪里？不同的代码分支吗？
