### ISSUE TITLE
前端这块以后主要维护vue3_dev分支吗？

### ISSUE THREAD

**Issue by thinkboy** [go-admin-team/go-admin-ui#232]
看上去几乎只维护基于antd的前端框架了是吗？这个版本是以后的master分支吗？顺便再问下antd版本是开源的吗？没找到代码。

**Comment by G-Akiraka** [comment]
vue3_dev 不是antd项目，是字节的 arco ui，日后会不会是master分支展示没有这个计划（毕竟后端代码生成暂时没做适配），目前vue3如果满足自己需求也可以用于开发。

**Comment by yhkkkkk** [comment]
antd版本的有开源吗

**Comment by G-Akiraka** [comment]
> antd版本的有开源吗

暂时没有，要看作者后面会不会考虑了。
