### ISSUE TITLE
node环境bug   @achrinza/node-ipc@9.2.2与commander@12.1.0

### ISSUE THREAD

**Issue by xTreeRoot** [go-admin-team/go-admin-ui#236]
# 分支
master
# node18Version  
v18.18.1 (npm v9.8.1)
# cmd
- yarn
# node18 Version Error
```
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.18.1"
error Found incompatible module.
```

# node16Version  
v16.20.2 (npm v8.19.4)
# cmd
- yarn
# node16 Version Error
```
error commander@12.1.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"
error Found incompatible module. 
```

**Comment by G-Akiraka** [comment]
node版本改成 18+

**Comment by luorenshu** [comment]
同样的问题，node切换到16.15.0， install 提示 
```
error commander@12.1.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"
error Found incompatible module. 
```

node切换到18以上提示
```
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "20.16.0"
error Found incompatible module.
```

**Comment by G-Akiraka** [comment]
> 同样的问题，node切换到16.15.0， install 提示
> 
> ```
> error commander@12.1.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"
> error Found incompatible module. 
> ```
> 
> node切换到18以上提示
> 
> ```
> error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "20.16.0"
> error Found incompatible module.
> ```

升级到 node 18+ 上面写了 大于或者等于 18

**Comment by wayfarer35** [comment]
用这个 
yarn config set ignore-engines true

**Comment by xTreeRoot** [comment]
> 用这个 yarn config set ignore-engines true

已经用别的管理系统入门了
