### ISSUE TITLE
创建的目录与菜单，点击左侧菜单一个栏目后，左侧菜单内容消失

### ISSUE THREAD

**Issue by 45253321** [go-admin-team/go-admin-ui#241]
![image](https://github.com/user-attachments/assets/2fe1d604-d237-4d2a-b1d4-2d0ecfd4e116)
点击后，左侧菜单栏内容全部消失
**已经解决，拼写错误!!!!**

**Comment by PysomeZh** [comment]
怎么解决的？最新master仍有这个问题
