### ISSUE TITLE
部署时使用相对路径

### ISSUE THREAD

**Issue by shengdoushi** [go-admin-team/go-admin-ui#27]
目前只能部署在站点根目录。可不可以修改 publicPath 为 "./" 这样部署时，可以随便自定义路径了

https://github.com/wenjianzhang/go-admin-ui/blob/ca6811ae64aea9928b9bcb19075c3337c8aff71e/vue.config.js#L29

**Comment by wenjianzhang** [comment]
您好，目前前端框架整体使用的是 vue-element-admin 整体解决方案，不知您为何有这样的想法，如果您有什么业务也可以将处理，或许可以提供一些思路帮助到您，谢谢您对go-admin的关注与支持！

**Comment by flashjay** [comment]
这个还是有用的，比如 /admin 作为站点管理模块，/ 留作它用。
