### ISSUE TITLE
SassError: expected selector.  /deep/

### ISSUE THREAD

**Issue by hatch1994** [go-admin-team/go-admin-ui#54]
I think you Cannot just use /deep/ on the top lvl？Also, try ::v-deep. 
like in Vue doc[Vue doc](https://vue-loader.vuejs.org/zh/guide/scoped-css.html#%E6%B7%B7%E7%94%A8%E6%9C%AC%E5%9C%B0%E5%92%8C%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F)

**Comment by hatch1994** [comment]
Is it because I use sass, not node-sass?

**Comment by wenjianzhang** [comment]
删除npm包，重新安装，node版本不要太高
