### ISSUE TITLE
dashboard keep-alive 失效

### ISSUE THREAD

**Issue by MoonBegonia** [go-admin-team/go-admin-ui#55]
偶然发现框架 keep-alive 失效，经过了解后发现 **路由 name 必须跟组件 name 一模一样。** 希望在文档或代码中提及。  
以及 dashboard 路由 name 应当与组件 name 一致。

``` diff
  {
    path: '/',
    component: Layout,
    redirect: '/dashboard',
    children: [
      {
        path: 'dashboard',
        component: () => import('@/views/dashboard/index'),
-       name: '首页',
+       name: 'Dashboard',
        meta: { title: '首页', icon: 'dashboard', affix: true }
      }
    ]
  },
```

我还发现菜单的 noCache 是写死的不缓存，我认为可以在创建菜单时提供 cache 选项自定义是否缓存。

**Comment by wenjianzhang** [comment]
非常感谢您提交的问题，我们将会在下一个版本做修正，谢谢！

**Comment by wenjianzhang** [comment]
针对这个问题，noCache即使设置为false还是不能够被缓存，https://github.com/PanJiaChen/vue-element-admin/issues/406 并没有比较好的方案，如果有好的方案可以提交pr，谢谢支持和关注
