### ISSUE TITLE
path-to-regexp 模块更新导致面包屑导航点击报错

### ISSUE THREAD

**Issue by MoonBegonia** [go-admin-team/go-admin-ui#62]
近期 path-to-regexp 从 `2.4` 升级到了 `6.1.0` 导致面包屑导航点击报错

**Comment by wenjianzhang** [comment]
不建议升级太高版本

**Comment by MoonBegonia** [comment]
![image](https://user-images.githubusercontent.com/26798347/102788498-a8936f00-43dd-11eb-875c-f62da6676487.png)
![image](https://user-images.githubusercontent.com/26798347/102788553-c1038980-43dd-11eb-880c-cb2fca719dab.png)
