### ISSUE TITLE
header 模糊搜索报错

### ISSUE THREAD

**Issue by oevery** [go-admin-team/go-admin-ui#68]
点击 header 的搜索按钮搜索报 `TypeError: Cannot read property 'join' of undefined`

**Comment by ahKevinXy** [comment]
## 哪里的header 搜索

**Comment by MoonBegonia** [comment]
@ahKevinXy 
![image](https://user-images.githubusercontent.com/26798347/91156482-c8987780-e6f6-11ea-924e-4289bc430ebb.png)

**Comment by ahKevinXy** [comment]
这个有什么用,我好像全部删除了

**Comment by G-Akiraka** [comment]
并没有做这个功能，而且这个是全局搜索
