### ISSUE TITLE
安装时出错

### ISSUE THREAD

**Issue by bzyy1024** [go-admin-team/go-admin-ui#84]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/soft/node-v14.15.0-linux-x64/bin/node',
1 verbose cli   '/soft/node/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint',
1 verbose cli   '--',
1 verbose cli   '--fix'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle go-admin@1.2.2~prelint: go-admin@1.2.2
6 info lifecycle go-admin@1.2.2~lint: go-admin@1.2.2
7 verbose lifecycle go-admin@1.2.2~lint: unsafe-perm in lifecycle true
8 verbose lifecycle go-admin@1.2.2~lint: PATH: /soft/node-v14.15.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/soft/go-admin-ui/node_modules/.bin:/home/bzyy/.local/bin:/home/bzyy/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/soft/node/bin
9 verbose lifecycle go-admin@1.2.2~lint: CWD: /soft/go-admin-ui
10 silly lifecycle go-admin@1.2.2~lint: Args: [ '-c', 'eslint --ext .js,.vue src "--fix"' ]
11 info lifecycle go-admin@1.2.2~lint: Failed to exec lint script
12 verbose stack Error: go-admin@1.2.2 lint: `eslint --ext .js,.vue src "--fix"`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/soft/node-v14.15.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1048:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
13 verbose pkgid go-admin@1.2.2
14 verbose cwd /soft/go-admin-ui
15 verbose Linux 4.18.0-147.5.1.el8_1.x86_64
16 verbose argv "/soft/node-v14.15.0-linux-x64/bin/node" "/soft/node/bin/npm" "run" "lint" "--" "--fix"
17 verbose node v14.15.0
18 verbose npm  v6.14.8
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error go-admin@1.2.2 lint: `eslint --ext .js,.vue src "--fix"`
23 error spawn ENOENT
24 error Failed at the go-admin@1.2.2 lint script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

node v14.15.0

**Comment by wenjianzhang** [comment]
node v14.12.0 不建议太高

**Comment by cheenbee** [comment]
https://nodejs.org/dist/ 可下载任意版本
