### ISSUE TITLE
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 14.x 的处理办法

### ISSUE THREAD

**Issue by 18019710907** [go-admin-team/go-admin-ui#87]
Failed to compile with 1 error                                                 下午8:15:12

 error  in ./src/styles/element-variables.scss

Syntax Error: Error: Missing binding /Users/jonny/go/src/go-admin-ui/node_modules/node-sass/vendor/darwin-x64-83/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 14.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 13.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.

 @ ./src/styles/element-variables.scss 4:14-237 14:3-18:5 15:22-245
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:9527&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by 18019710907** [comment]
lijiayi@lijiayideMacBook-Pro go-admin-ui % npm -v
6.14.10
lijiayi@lijiayideMacBook-Pro go-admin-ui % node -v
v14.15.3

**Comment by wenjianzhang** [comment]
npm 安装的包删掉重新安装

**Comment by 18019710907** [comment]
npm rebuild node-sass  我执行一下这个就好了~
![image](https://user-images.githubusercontent.com/17740504/102850661-ebdcf480-4454-11eb-9f51-fa8be5b614bc.png)

**Comment by GeekByte** [comment]
若不是来翻翻 issues 还真不知道怎么解决，现在 OSX 上 node.js14.x 没有 Run `npm rebuild node-sass` 这个提示了。

不过，我是用 `npm rebuild node-sass` 一样解决了这个问题。
