### ISSUE TITLE
请问系统必须至少有二级菜单吗？

### ISSUE THREAD

**Issue by hvvjoy** [go-admin-team/go-admin-ui#90]
你好，最近做一个教学的系统，为了方便，有些菜单不想弄成二级的，想让用户直接访问（图1）：
![image](https://user-images.githubusercontent.com/3402309/106151743-a4febf00-61b7-11eb-843f-8671b6d07d9c.png)

但是配置好后，点这个链接，却没有了左边的菜单栏（图2）：

![image](https://user-images.githubusercontent.com/3402309/106151980-e7c09700-61b7-11eb-99cd-d98cc943db22.png)

请问系统在不需要大改的情况下，有没有可能设置正常显示的一级菜单呢？ 谢谢！

**Comment by wenjianzhang** [comment]
以及菜单需要调整菜单结构，可以参考element-ui和element-vue-admin的说明文档
