### ISSUE TITLE
getConfigKey 接口请求参数有误

### ISSUE THREAD

**Issue by SealinGp** [go-admin-team/go-admin-ui#93]
在文件 src/api/system/config.js的21行, 函数getConfigKey 有误,应该是 get /api/v1/configKey/xxx, 而不是post,页面会报错,
根据后端go-admin的接口文档以及代码来看发现的

**Comment by SealinGp** [comment]
src/api/system/config.js 第6行,listConfig函数中的url /api/v1/config 应该为 /api/v1/configList

**Comment by wenjianzhang** [comment]
该问题新版本已经处理；
